# Generated by Django 5.2 on 2026-05-21 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Especiadidad',
            new_name='Especialidad',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='servicio',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('TI', 'Targeta de Identidad'), ('CC', 'Cédula de Ciudadanía'), ('PASSPORT', 'Pasaporte'), ('OTRO', '')], default='OTRO', max_length=20),
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='sistema.servicio'),
            preserve_default=False,
        ),
    ]
