# Generated by Django 5.2 on 2026-05-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_rename_especiadidad_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(help_text='Ingrese su correo electrónico ', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
