# Generated by Django 5.2 on 2026-05-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_alter_cliente_email_alter_cliente_numero_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cédula de Ciudadanía'), ('PASSPORT', 'Pasaporte'), ('OTRO', 'Otro')], default='OTRO', max_length=20),
        ),
        migrations.RemoveField(
            model_name='medico',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidad',
            field=models.ManyToManyField(related_name='medicos', to='sistema.especialidad'),
        ),
    ]
